In [1]:
from sklearn.datasets import fetch_mldata
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pylab as plt
import time
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score           # 정확도 채점
from sklearn.model_selection import cross_val_score  
from sklearn.preprocessing import MinMaxScaler

In [2]:
t1 = time.time()
mnist_train_data_path="C:/Users/1-12/train.csv"
train = np.genfromtxt(mnist_train_data_path,delimiter = ',',skip_header=1).astype(np.dtype('uint8'))
t2 = time.time()
print("process time:",t2-t1)
print(train)

process time: 19.749032497406006
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]


In [3]:
train

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [3]:
t1 = time.time()
mnist_test_data_path="C:/Users/1-12/test.csv"
test = np.genfromtxt(mnist_test_data_path,delimiter = ',',skip_header=1).astype(np.dtype('uint8'))
t2 = time.time()

print("process time:",t2-t1)
print(test)

process time: 13.359416961669922
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
print(len(train))
print(len(test))

42000
28000


In [5]:
train.shape

(42000, 785)

In [6]:
test.shape

(28000, 784)

In [7]:
train_data = train[:,1:]
train_labels = train[:,0]

In [8]:
len(train)

42000

In [9]:
train.shape

(42000, 785)

In [10]:
test.shape

(28000, 784)

In [11]:
train_data.shape

(42000, 784)

In [12]:
print(train_data)
print()
print(train_labels)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

[1 0 1 ... 7 6 9]


In [13]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [14]:
unique, counts = np.unique(train_labels,return_counts=True)
print(np.array((unique,counts)).T)

[[   0 4132]
 [   1 4684]
 [   2 4177]
 [   3 4351]
 [   4 4072]
 [   5 3795]
 [   6 4137]
 [   7 4401]
 [   8 4063]
 [   9 4188]]


PCA

In [15]:
from sklearn.decomposition import PCA

In [16]:
num_comp = 61
pca = PCA(n_components = num_comp)

In [17]:
pca.fit(train_data)

PCA(copy=True, iterated_power='auto', n_components=61, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [18]:
np.sum(pca.explained_variance_ratio_)

0.8556847271892309

In [19]:
train_ext = pca.transform(train_data)
print(train_ext.shape)

(42000, 61)


In [20]:
test_ext = pca.transform(test)
print(test_ext.shape)

(28000, 61)


In [21]:
# min_max_scaler = MinMaxScaler()

In [22]:
# train_norm = min_max_scaler.fit_transform(train_ext)
# test_norm = min_max_scaler.fit_transform(test_ext)

In [23]:
knn = KNeighborsClassifier(n_neighbors =5, n_jobs = -1)
knn.fit(train_ext,train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')

In [24]:
# train_norm.shape

In [25]:
# tes_norm.shape

In [26]:
pred = knn.predict(test_ext)

저장하기

In [27]:
img_id = []

for i in range(1, len(test)+1):
    img_id.append(i)
    
predMNIST = pd.DataFrame({"imageId":img_id,"Label":pred})

out_path = 'C:/Users/1-12/Desktop/train_PCA61_k=5_quad_weight.csv'
predMNIST.to_csv(out_path, index = False)

테스트하기

In [197]:
mnist = fetch_mldata('MNIST original')

(train_data_my2,test_data_my2,train_labels_my2,test_labels_my2) = train_test_split(np.array(mnist.data),mnist.target,test_size=0.4, random_state=1239)

print(len(train_data_my2))
print(len(test_data_my2))

42000
28000


C:\Users\1-12\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:85: DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22. Please use fetch_openml.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\1-12\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:85: DeprecationWarning: Function mldata_filename is deprecated; mldata_filename was deprecated in version 0.20 and will be removed in version 0.22. Please use fetch_openml.
  warnings.warn(msg, category=DeprecationWarning)


In [198]:
test_exttest = pca.fit_transform(test_data_my2)
print(test_exttest.shape)

(28000, 61)


In [199]:
pred1 = knn.predict(test_exttest)
print(accuracy_score(test_labels_my2, pred1))

0.8831785714285715


In [200]:
from sklearn.model_selection import cross_val_score

In [201]:
cross_val_score(knn,train_ext, train_labels, cv = 5)

array([0.97227841, 0.97322385, 0.969163  , 0.9685602 , 0.97427346])

트레인데이터 2배로 늘리고 차원축소

In [32]:
from sklearn.decomposition import PCA

train_double= np.concatenate((train,train),axis = 0)
train_double= np.concatenate((train_double,train_double),axis = 0)
print(train_double.shape)

train_double_data = train_double[:,1:]
train_double_labels = train_double[:,0]
print(train_double_data.shape)
print(train_double_labels.shape)

num_comp = 61
pca = PCA(n_components = num_comp)
pca.fit(train_double_data)
train_double_ext = pca.transform(train_double_data)
test_ext = pca.transform(test)


knn = KNeighborsClassifier(n_neighbors = 5, n_jobs = -1)
knn.fit(train_double_ext,train_double_labels)
pred = knn.predict(test_ext)




from sklearn.model_selection import cross_val_score
cross_val_score(knn,train_double_ext , train_double_labels, cv = 5)

(168000, 785)
(168000, 784)
(168000,)


array([1., 1., 1., 1., 1.])

저장하기

In [34]:
img_id = []

for i in range(1, len(test)+1):
    img_id.append(i)
    
predMNIST = pd.DataFrame({"imageId":img_id,"Label":pred})

out_path = 'C:/Users/1-12/Desktop/train_PCA61_k=5_quad.csv'
predMNIST.to_csv(out_path, index = False)